[[session]]
name = "karabiner"
path = "~/.config/karabiner"
startup_command = "nvim karabiner.json"

[[session]]
name = "aerospace"
path = "~/.config/aerospace"
startup_command = "nvim aerospace.toml"

[[session]]
name = "Patiss'Aulotte - Admin"
path = "~/Developer/PatissAulotte/admin"
startup_command = "tmux split-window -v -l 10 dev && tmux select-pane -t :.+ && nvim"

[[session]]
name = "Patiss'Aulotte - API"
path = "~/Developer/PatissAulotte/api"
startup_command = "tmux split-window -v -l 10 dev && tmux select-pane -t :.+ && nvim"
