#!/usr/bin/env bash
tmux split-window -v -l 10
tmux send-keys ". .venv/bin/activate && fastapi dev app/app.py" Enter
tmux select-pane -t :.+
tmux send-keys ". .venv/bin/activate" Enter
tmux send-keys "nvim" Enter
