[[session]]
name = "Patiss'Aulotte - Admin"
path = "~/Developer/PatissAulotte/admin"
startup_script = "~/.config/sesh/scripts/angular_conf"

[[session]]
name = "Patiss'Aulotte - API"
path = "~/Developer/PatissAulotte/api-python"
startup_script = "~/.config/sesh/scripts/patissaulotte_python_conf"
