#!/usr/bin/env bash
tmux split-window -v -l 10
tmux send-keys "conda activate patissaulotte && django runserver" Enter
tmux select-pane -t :.+
tmux send-keys "conda activate patissaulotte" Enter
tmux send-keys "nvim" Enter
