[tools]
# global tool versions go here
# you can set these with `mise use -g`
node = "latest"
python = ['3.12', '3.13']
rust = "latest"
go = "latest"
ruby = "latest"
usage = "latest"

[settings]
experimental = true
